CREAT DATABASE SpotifyDatabase

USE SpotifyDatabase;
GO

CREATE TABLE Users
(
    UserId INT PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    RegisteredDate DATETIME NOT NULL
);

CREATE TABLE Artists
(
    ArtistId INT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Biography NVARCHAR(250) NOT NULL,
    Origin NVARCHAR(50) NOT NULL
);


CREATE TABLE Songs
(
    SongId INT PRIMARY KEY,
    Title NVARCHAR(50) NOT NULL,
    Duration TIME NOT NULL,
    ReleaseDate DATETIME NOT NULL,
    Genre NVARCHAR(20) NOT NULL,
    ArtistId INT NOT NULL,
    FOREIGN KEY (ArtistId) REFERENCES Artists (ArtistId) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Albums
(
    AlbumId INT PRIMARY KEY,
    Title NVARCHAR(50) NOT NULL,
    ReleaseDate DATETIME NOT NULL,
    Genre NVARCHAR(20) NOT NULL,
    SongId INT NOT NULL,
    ArtistId INT NOT NULL,
    FOREIGN KEY (SongId) REFERENCES Songs (SongId) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (ArtistId) REFERENCES Artists (ArtistId) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Playlists
(
    PlaylistId INT PRIMARY KEY,
    Title NVARCHAR(50) NOT NULL,
    CreationDate DATETIME NOT NULL,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users (UserId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PlaylistSongs
(
    PlaylistSongId INT PRIMARY KEY,
    Position INT NOT NULL,
    PlaylistId INT NOT NULL,
    SongId INT NOT NULL,
    FOREIGN KEY (PlaylistId) REFERENCES Playlists (PlaylistId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SongId) REFERENCES Songs (SongId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE UserLikes
(
    UserLikesId INT PRIMARY KEY,
    UserId INT NOT NULL,
    SongId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users (UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SongId) REFERENCES Songs (SongId) ON DELETE CASCADE ON UPDATE CASCADE
);

GO
